datalake_transformations:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: "E:/Batdorj/code_proj/llm_agent_mcp-main/llm_agent_mcp-main/datalake.db"
      schema: "main"
      schema_directory: "E:/Batdorj/code_proj/llm_agent_mcp-main/llm_agent_mcp-main/dbt/schemas"
      schemas_and_paths:
        main: "E:/Batdorj/code_proj/llm_agent_mcp-main/llm_agent_mcp-main/datalake.db"
